language: node_js
node_js:
  - "node"

script:
  - npm install
  - npm test
  # - npm run build
# deploy:
#   provider: heroku
#   app:
#     master: recipy-app
#   api_key:
#     secure: 7f16dc80-e8c4-4298-877b-b1d120a1f480
#   true:
#     repo: AJSMonty/Recipy
